name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: compile test
      id: compile-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: compile test
        setup-command: ''
        command: gcc *.c
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILE-TEST_RESULTS: "${{steps.compile-test.outputs.result}}"
      with:
        runners: compile-test
